name: newborn-metabolic-health
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.*
  - pytorch=1.6.*
  - pytorch-lightning=1.4.*
  - torchmetrics=0.4.0
  - pandas
  - jupyterlab
  - matplotlib
  - numpy
  - pip=23.*
  - scikit-learn
  - scipy
  - seaborn
  - wandb
  - xlsxwriter
  - dvc
  - dvc-gs
  - pip:
    - pytest
    - xgboost==1.4.*
    - pysubgroup==0.7.*
    - pyyaml
    - combat
    - yellowbrick==1.5
