name: newborn-metabolic-health
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - catboost
  - jupyterlab=1.2.4
  - matplotlib=3.1.2
  - numpy=1.17.2
  - pandas=1.0.1
  - pip=19.3.1
  - python=3.7.6
  - scikit-learn=0.24.*
  - scipy=1.4.1
  - seaborn=0.9.0
  - pytorch=1.6.*
  - torchvision
  - wandb
  - pip:
    - pytest==5.3.2
    - pysubgroup
    - xgboost
