name: newborn-metabolic-health
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*
  - pytorch=1.6.*
  - pytorch-lightning=1.4.*
  - torchmetrics=0.6.*
  - pandas=2.1.*
  - jupyterlab=1.*
  - matplotlib=3.*
  - numpy=1.*
  - pip=23.*
  - scikit-learn=1.3.*
  - scipy=1.*
  - seaborn=0.13.*
  - wandb=0.19.*
  - xlsxwriter
  - dvc
  - dvc-gs
  - pip:
    - pytest
    - xgboost==1.4.*
    - pysubgroup==0.7.*
    - pyyaml
    - combat
    - yellowbrick==1.5
