name: newborn-metabolic-health
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - jupyterlab=1.2.4
  - matplotlib=3.1.2
  - numpy=1.20.*
  - pandas=1.0.1
  - pip=19.3.1
  - python=3.7.6
  - scikit-learn=1.0.2
  - scipy=1.4.1
  - seaborn=0.11.*
  - seaborn-base=0.11.*
  - pytorch=1.6.*
  - torchvision
  - xlsxwriter
  - pip:
    - pytest==5.3.2
    - xgboost==1.4.*
    - pysubgroup==0.7.*
    - pyyaml==6.0.1
    - combat==0.3.*
    - yellowbrick==1.5
