name: newborn-metabolic-health
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - dvc
  - dvc-gs
  - jupyterlab=1.*
  - pytorch-lightning=1.5.*
  - matplotlib=3.*
  - numpy=1.*
  - pandas=1.*
  - pip
  - python=3.9.*
  - scikit-learn=1.0.*
  - scipy=1.*
  - seaborn=0.13.*
  - pytorch=1.6.*
  - torchvision
  - wandb
  - xlsxwriter
  - pip:
    - pytest
    - xgboost==1.4.*
    - pysubgroup==0.7.*
    - pyyaml
    - combat
    - yellowbrick==1.5
