# Quantile parameters for feature transformation (list-like)
quantile_cuts: [2, 3, 5]
# Subgroup discovery parameters
depth: 4
# Percent of the entire dataset to consider top K
top_k_percent_data: 20

# Parameters by evaluation metric
all_outcomes: ["ivh_any", "rop_any", "nec_any", "bpd_any"]
evaluation_outcomes: ["ivh_any", "nec_any", "bpd_any"]
evaluation_parameters:
  AUROC:
    alphas:
      bpd_any: 0.060
      ivh_any: 0.060
      nec_any: 0.060
    sizes:
      bpd_any: 200
      ivh_any: 300
      nec_any: 200

# Debug configurations
debug:
  quantile_cuts: [3]
  depth: 2
  top_k_percent_data: 10
