id: row_id
features:
  - ALA
  - ARG
  - C02
  - C03
  - C03DC
  - C04
  - C04DC
  - C05
  - C051
  - C05DC
  - C05OH
  - C06
  - C08
  - C081
  - C10
  - C101
  - C12
  - C121
  - C14
  - C141
  - C142
  - C14OH
  - C16
  - C16OH
  - C18
  - C181
  - C181OH
  - C182
  - C18OH
  - CIT
  - FC
  - GLY
  - MET
  - ORN
  - OXP
  - PHE
  - PRO
  - R03D10
  - R05D03D
  - R14_12
  - R16O16
  - R3_2
  - R5_3
  - R8_10
  - RA_O
  - RC_A
  - RF_C
  - RF_Y
  - RL_A
  - RO_C
  - RV_F
  - SA
  - TYR
  - VAL
  - XLE
outcomes: [bpd_any, nec_any, rop_any]
